name: build-zt-pylon-aarch64
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare workspace
        uses: actions/checkout@v4

      - name: Build in aarch64 userland (QEMU)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04    # older glibc => better compatibility on router
          install: |
            apt-get update
            apt-get install -y build-essential clang cmake git pkg-config
          run: |
            set -eux
            cd /tmp
            git clone --recurse-submodules https://github.com/zerotier/pylon.git
            cd pylon
            make -j"$(nproc)"
            strip pylon || true
            mkdir -p "$GITHUB_WORKSPACE/out"
            cp -f pylon "$GITHUB_WORKSPACE/out/pylon"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pylon-aarch64
          path: out/pylon
