name: build-zt-pylon-aarch64
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04-arm64   # << native arm64 (no QEMU!)
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cmake git pkg-config
      - name: Clone Pylon (with submodules)
        run: git clone --recurse-submodules https://github.com/zerotier/pylon.git
      - name: Build
        run: |
          set -eux
          cd pylon
          make -j"$(nproc)"
          strip pylon || true
          mkdir -p "$GITHUB_WORKSPACE/out"
          cp -f pylon "$GITHUB_WORKSPACE/out/pylon"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pylon-aarch64
          path: out/pylon